apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        ports:
        - containerPort: 80
        # env:
        # - name: PMA_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: customapp-configmap
        #       key: PMA_HOST
        # - name: PMA_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: customapp-configmap
        #       key: PMA_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

